version: '3.7'

services:
  lwjgl:
    image: lwjgl/website:latest
    ports:
      - 80:80
    command: node server/index.mjs --s3proxy --test
    volumes:
      - type: bind
        source: ./public/js
        target: /srv/public/js
