export const SELECT_TYPE = 'BUILD/SELECT_TYPE';
export const SELECT_MODE = 'BUILD/SELECT_MODE';
export const SELECT_PRESET = 'BUILD/SELECT_PRESET';
export const SELECT_LANGUAGE = 'BUILD/SELECT_LANGUAGE';
export const SELECT_VERSION = 'BUILD/SELECT_VERSION';
export const TOGGLE_DESCRIPTIONS = 'BUILD/TOGGLE_DESCRIPTIONS';
export const TOGGLE_SOURCE = 'BUILD/TOGGLE_SOURCE';
export const TOGGLE_JAVADOC = 'BUILD/TOGGLE_JAVADOC';
export const TOGGLE_COMPACT = 'BUILD/TOGGLE_COMPACT';
export const TOGGLE_HARDCODED = 'BUILD/TOGGLE_HARDCODED';
export const TOGGLE_PLATFORM = 'BUILD/TOGGLE_PLATFORM';
// export const ERROR_SET = 'BUILD/ERROR_SET';
export const TOGGLE_ARTIFACT = 'BUILD/TOGGLE_ARTIFACT';

export const DOWNLOAD_INIT = 'BUILD/DOWNLOAD_INIT';
export const DOWNLOAD_COMPLETE = 'BUILD/DOWNLOAD_COMPLETE';
export const DOWNLOAD_LOG = 'BUILD/DOWNLOAD_LOG';
